function featureVector = charObj_to_featureVector(char_obj)
    featureVector(1) = char_obj.Features.Area;
    featureVector(2) = char_obj.Features.Perimeter;
    featureVector(3) = char_obj.Features.Euler;
    featureVector(4) = char_obj.Features.Circularity;
    featureVector(5) = char_obj.Features.Centroids.X;
    featureVector(6) = char_obj.Features.Centroids.Y;
    featureVector(7) = char_obj.Features.Strokes.H;
    featureVector(8) = char_obj.Features.Strokes.V;
    featureVector(9) = char_obj.Features.Symmetries.H;
    featureVector(10) = char_obj.Features.Symmetries.V;
    featureVector(11) = char_obj.Features.Aspect_Ratio;
    featureVector(12) = char_obj.Features.Moments(1);
    featureVector(13) = char_obj.Features.Moments(2);
    featureVector(14) = char_obj.Features.Moments(3);
    featureVector(15) = char_obj.Features.Moments(4);
    featureVector(16) = char_obj.Features.Moments(5);
    featureVector(17) = char_obj.Features.Moments(6);
    featureVector(18) = char_obj.Features.Moments(7);
    featureVector(19) = char_obj.Features.Moments(8);
    featureVector(20) = char_obj.Features.Moments(9);
    featureVector(21) = char_obj.Features.Moments(10);
end